name: Fetch Package Updates on Pypi

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 0'

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Execute write_plugins_doc created as a script by setup.py
      run: |
        write_plugins_doc
    - name: Commit files
      run: |
        git config --local user.name "rgeneaux"
        git add .
        if ! git diff-index --quiet HEAD; then
          git commit -m "Auto-update package list"
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
